DROP TABLE if EXISTS `ANIME_TYPE`;
CREATE TABLE `ANIME_TYPE` (
  `ID` int(20) NOT NULL AUTO_INCREMENT COMMENT '动漫类型ID',
  `ANIME_TYPE_ID` int(20) DEFAULT NULL COMMENT '动漫之家类型名',
  `ANIME_TYPE_NAME` varchar(30) DEFAULT NULL COMMENT '动漫类型名',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='动漫类型表';

ALTER TABLE anime_info CHANGE  ANIME_TYPE_ID ANIME_TYPE_ID_LS VARCHAR(30) DEFAULT NULL COMMENT '动漫类型' ;
alter table anime_info modify ANIME_TYPE_ID_LS varchar(100) ; 