CREATE TABLE `proxyls` (
  `ID` int(20) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `PROXY_TYPE` varchar(20) DEFAULT NULL COMMENT '代理类型',
  `PROXY_ADDR` varchar(30) DEFAULT NULL COMMENT '代理地址',
  `PROXY_PORT` varchar(20) DEFAULT NULL COMMENT '代理端口',
  `PROXY_ADD_TIME` bigint(20) DEFAULT NULL COMMENT '代理添加时间',
  `PROXY_CHECK_TIME` bigint(20) DEFAULT NULL COMMENT '代理检验时间',
  `PROXY_MD5` varchar(255) DEFAULT NULL COMMENT '代理MD5',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='代理表';
