CREATE TABLE `anime_timetable` (
  `ID` int(20) NOT NULL AUTO_INCREMENT,
  `ANIME_BID` int(20) DEFAULT NULL COMMENT 'anitama动漫ID',
  `ANIME_ID` bigint(20) DEFAULT NULL COMMENT '动漫ID',
  `ANIME_NAME` varchar(100) DEFAULT NULL COMMENT '动漫名称',
  `ANIME_COVER` varchar(255) DEFAULT NULL COMMENT '动漫封面图片链接',
  `ANIME_VERTICAL_COVER` varchar(255) DEFAULT NULL COMMENT '动漫图片链接',
  `ANIME_PLAY_DATE` varchar(20) DEFAULT NULL COMMENT '动漫播放日期',
  `ANIME_PLAY_TIME` varchar(20) DEFAULT NULL COMMENT '国内动漫播放时间',
  `ANIME_ORIGIN_TIME` varchar(20) DEFAULT NULL COMMENT '制作国家动漫播放时间',
  `ANIME_PLAY_SITE` varchar(255) DEFAULT NULL COMMENT '国内动漫播放网站',
  `ANIME_ORIGIN_STATION` varchar(20) DEFAULT NULL COMMENT '制作国家动漫播放电视台',
  `ANIME_PLAY_URL` text DEFAULT NULL COMMENT '国内动漫播放网站地址',
  `ANIME_PLAY_EPISODE` varchar(20) DEFAULT NULL COMMENT '动漫播放集数',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COMMENT='动漫更新时间表';

